### ISSUE TITLE
Searching for program: No such file or directory, gotests

### ISSUE THREAD

**Issue by chrisalcantara** [damienlevin/GoTests-Emacs#3]
Getting this error running Emacs 26.2 on macOS 10.12.6. 

I placed the gotests.el file in my `.emacs.d/` folder and I get the above error when I run `gotests-region`.

`gotests` does run for me on the command line.

**Comment by elzorrorebelde** [comment]
this probably because Emacs did not inherited the PATH variable.

What's the value of PATH inside Emacs? (run `(getenv "PATH")` somewhere to check)

**Comment by chrisalcantara** [comment]
I've since solved this issue by ensuring Emacs could read the `PATH` variable.
